#! /bin/bash

#CMS - CMS Made Simple
#(c)2004 by Leendert Meyer <leen.meyer@home.nl>
#This project's homepage is: http://cmsmadesimple.sf.net
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

VERSION="${0##*/} Version 0.1"

USAGE="Usage: ${0##*/} -f|--force | -t|--test | -h|--help | -v|--version | -U|--usage [path]"

HELP="This is a helper script to svn-propset.

This script allows to skip the setting of a property if the property is already present.
"

FORCE=""
TEST=""
while true; do
  case $1 in
    -f|--force)
		FORCE="yes"
		shift
		;;
    -t|--test)
		TEST="echo"
		shift
		;;
    -u|--usage)
  		echo "$USAGE"
		exit 1
		;;
    -v|--version)
  		echo "$VERSION"
		exit 1
		;;
    -h|--help)
  		echo "$VERSION"
		echo
  		echo "$USAGE"
		echo
  		echo "$HELP"
		exit 1
		;;
    *)
		break
		;;
  esac
done

PROP_TYP="$1"
PROP_VAL="$2"
PROP_FIL="$3"

# I suppose this is superfluous:
[ "$PROP_TYP" = "svn:executable" -a -z "$PROP_VAL" ] && PROP_VAL="*"

# only set a property if it is not already defined OR if the -f|--force flag was used.
CUR_PROP="`svn proplist \"$PROP_FIL\" | grep \"$PROP_TYP\"`"
[ -z "$CUR_PROP" -o "$FORCE" = "yes" ] && $TEST svn propset "$PROP_TYP" "$PROP_VAL" "$PROP_FIL"
